package pointnet

import (
	"encoding/binary"
	"math"
	"os"
	"testing"

	"lazybg/internal/bg"
	"lazybg/internal/calibrate"
	"lazybg/internal/perceive"
	"lazybg/internal/perceive/boardsynth"
)

// The fixture pair (random-weight tiny model + input/expected-logits vector)
// is generated by ml/export_go.py --random-tiny. The Go forward pass must
// reproduce the folded torch reference.
func TestForward_ParityWithTorch(t *testing.T) {
	net, err := Load("../../../testdata/pointnet/pointreader.bin")
	if err != nil {
		t.Fatal(err)
	}

	raw, err := os.ReadFile("../../../testdata/pointnet/testvec.bin")
	if err != nil {
		t.Fatal(err)
	}
	c := int(binary.LittleEndian.Uint32(raw[0:]))
	h := int(binary.LittleEndian.Uint32(raw[4:]))
	w := int(binary.LittleEndian.Uint32(raw[8:]))
	if c != 3 || h != InH || w != InW {
		t.Fatalf("testvec dims %dx%dx%d, want 3x%dx%d", c, h, w, InH, InW)
	}
	off := 12
	input := make([]float32, c*h*w)
	for i := range input {
		input[i] = math.Float32frombits(binary.LittleEndian.Uint32(raw[off+4*i:]))
	}
	off += 4 * len(input)
	n := int(binary.LittleEndian.Uint32(raw[off:]))
	off += 4
	want := make([]float32, n)
	for i := range want {
		want[i] = math.Float32frombits(binary.LittleEndian.Uint32(raw[off+4*i:]))
	}

	got := net.Forward(input)
	if len(got) != len(want) {
		t.Fatalf("logits = %d, want %d", len(got), len(want))
	}
	for i := range got {
		if d := math.Abs(float64(got[i] - want[i])); d > 1e-4 {
			t.Errorf("logit %d = %v, want %v (|Δ|=%.2e)", i, got[i], want[i], d)
		}
	}
}

func TestLoad_RejectsGarbage(t *testing.T) {
	if _, err := Load("/nonexistent"); err == nil {
		t.Error("expected error for missing file")
	}
	f, _ := os.CreateTemp(t.TempDir(), "bad")
	f.WriteString("not a model")
	f.Close()
	if _, err := Load(f.Name()); err == nil {
		t.Error("expected error for bad magic")
	}
}

// Reader mechanics: 24 classified points with sane confidences on a synthetic
// rectified board (the fixture net is random — accuracy is evaluated on real
// data in internal/e2e with the trained model).
func TestReader_Mechanics(t *testing.T) {
	net, err := Load("../../../testdata/pointnet/pointreader.bin")
	if err != nil {
		t.Fatal(err)
	}
	cb := calibrate.DefaultCanonical()
	colors := boardsynth.DefaultColors()
	img := boardsynth.Render(cb, boardsynth.LayoutFromBoard(bg.StandardStart()), colors)

	ob := Reader{Net: net}.Read(img, cb)
	for p := 1; p <= 24; p++ {
		o := ob.Points[p]
		if o.Confidence <= 0 || o.Confidence > 1 {
			t.Errorf("point %d confidence %v out of range", p, o.Confidence)
		}
		if o.Count < 0 || o.Count > 6 {
			t.Errorf("point %d count %d out of range", p, o.Count)
		}
		if o.Count == 0 && o.Side != perceive.None {
			t.Errorf("point %d empty but side %v", p, o.Side)
		}
	}
}
