// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteFile(arg1:string):Promise<void>;

export function OpenDatabaseDialog():Promise<string>;

export function OpenPositionDialog():Promise<main.FileDialogResponse>;

export function SaveDatabaseDialog():Promise<string>;

export function ShowAlert(arg1:string):Promise<void>;
