// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function OpenDatabaseDialog() {
  return window['go']['main']['App']['OpenDatabaseDialog']();
}

export function OpenPositionDialog() {
  return window['go']['main']['App']['OpenPositionDialog']();
}

export function SaveDatabaseDialog() {
  return window['go']['main']['App']['SaveDatabaseDialog']();
}

export function ShowAlert(arg1) {
  return window['go']['main']['App']['ShowAlert'](arg1);
}
