// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteFile(arg1:string):Promise<void>;

export function ExportMatchTextDialog():Promise<string>;

export function GetCandidateMoves(arg1:main.Position):Promise<Array<main.CandidateMove>>;

export function OpenPositionDialog():Promise<main.FileDialogResponse>;

export function OpenTranscriptionDialog():Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveTranscriptionDialog():Promise<string>;

export function ShowAlert(arg1:string):Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
