// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function OpenPositionDialog() {
  return window['go']['main']['App']['OpenPositionDialog']();
}

export function OpenTranscriptionDialog() {
  return window['go']['main']['App']['OpenTranscriptionDialog']();
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function SaveTranscriptionDialog() {
  return window['go']['main']['App']['SaveTranscriptionDialog']();
}

export function ShowAlert(arg1) {
  return window['go']['main']['App']['ShowAlert'](arg1);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
