// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadConfig():Promise<main.Config>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveWindowDimensions(arg1:number,arg2:number):Promise<void>;
